"""Added password column to tenant_admins table

Revision ID: 0f0196b4ae04
Revises: 68c78b44d931
Create Date: 2024-02-16 14:17:14.184495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0196b4ae04'
down_revision: Union[str, None] = '68c78b44d931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_admins', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_admins', 'password')
    # ### end Alembic commands ###
